In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
datos = sns.load_dataset('titanic')
datos

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [4]:
datos.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
datos.drop('embarked', axis=1, inplace=True)
datos.drop('class', axis=1, inplace=True)
datos.drop('who', axis=1, inplace=True)
datos.drop('deck', axis=1, inplace=True)
datos.drop('embark_town', axis=1, inplace=True)
datos.drop('alive', axis=1, inplace=True)
datos.drop('alone', axis=1, inplace=True)
datos

     survived  pclass     sex   age  sibsp  parch     fare  adult_male
0           0       3    male  22.0      1      0   7.2500        True
1           1       1  female  38.0      1      0  71.2833       False
2           1       3  female  26.0      0      0   7.9250       False
3           1       1  female  35.0      1      0  53.1000       False
4           0       3    male  35.0      0      0   8.0500        True
..        ...     ...     ...   ...    ...    ...      ...         ...
886         0       2    male  27.0      0      0  13.0000        True
887         1       1  female  19.0      0      0  30.0000       False
888         0       3  female   NaN      1      2  23.4500       False
889         1       1    male  26.0      0      0  30.0000        True
890         0       3    male  32.0      0      0   7.7500        True

[891 rows x 8 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
codificador = LabelEncoder()
datos['sex'] = codificador.fit_transform(datos["sex"])

In [7]:
copiaDatos = datos.copy()

In [8]:
# dividir el conjunto en X (explicativas) y Y (respuesta)
y = datos['survived']
datos.drop('survived', axis=1, inplace=True)
datos

     pclass  sex   age  sibsp  parch     fare  adult_male
0         3    1  22.0      1      0   7.2500        True
1         1    0  38.0      1      0  71.2833       False
2         3    0  26.0      0      0   7.9250       False
3         1    0  35.0      1      0  53.1000       False
4         3    1  35.0      0      0   8.0500        True
..      ...  ...   ...    ...    ...      ...         ...
886       2    1  27.0      0      0  13.0000        True
887       1    0  19.0      0      0  30.0000       False
888       3    0   NaN      1      2  23.4500       False
889       1    1  26.0      0      0  30.0000        True
890       3    1  32.0      0      0   7.7500        True

[891 rows x 7 columns]

In [9]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   pclass      891 non-null    int64
 1   sex         891 non-null    int32
 2   age         714 non-null    float64
 3   sibsp       891 non-null    int64
 4   parch       891 non-null    int64
 5   fare        891 non-null    float64
 6   adult_male  891 non-null    bool
dtypes: bool(1), float64(2), int32(1), int64(3)
memory usage: 39.3 KB

In [10]:
print(datos.isnull().sum())

pclass          0
sex             0
age           177
sibsp           0
parch           0
fare            0
adult_male      0
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(datos, y, test_size = 0.3)

In [12]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [13]:
lr.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

## Eliminar columnas con valores faltantes

In [ ]:
datosActualizados = datos.dropna(axis=1)
datosActualizados

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(datosActualizados, y, test_size = 0.3)
lr.fit(X_train, y_train)
pred = lr.predict(X_test)

In [ ]:
pred

In [ ]:
from sklearn import metrics

In [ ]:
print(metrics.accuracy_score(pred, y_test))

## Rellenar datos faltante -inputar

Imputar con:
- Media: Promedio de los datos (se ve afectada por valores extremo)
- Mediana: Valores que se encuentran justamente en la posición central de la serie de datos ordenada
- Moda: El más frecuente.

In [ ]:
datosRelleno = CopiaDatos.copy()
datosRelleno['age'] = datosRelleno['age'].fillna(datosRelleno['age'].mean())
datosRelleno.info()

In [ ]:
# Segmentar los grupo en entrenamiento y pruebas
y = datosRelleno['survived']
datosRelleno.drop('survived', axis=1, inplace=True)
X_train, X_test, Y_train, Y_test = train_test_split(datosRelleno, y, test_size=0.3)
lr.fit(X_train, Y_train)
pred = lr.predict(X_test)
print(metrics.accuracy_score(pred, Y_test))

## Otras formas de imputación
- Interpolación lineal
- Rellenar con el dato de la siguiente fila
- Agregar una columna

In [14]:
imputados = copiaDatos.copy()
imputados["age missing"] = imputados["age"].isnull()
imputados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    int32
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   adult_male   891 non-null    bool
 8   age missing  891 non-null    bool
dtypes: bool(2), float64(2), int32(1), int64(4)
memory usage: 47.1 KB